### ISSUE TITLE
Custom field checkboxes never show results

### ISSUE THREAD

**Issue by crystalenka** [nikosdion/plg_system_filtermagic#3]
If there is a custom field of type checkboxes in an article, the article never returns as a result.

I checked the database and it seems the values are stored like so (in a subform):

```
{"field42":["children-families","youth"]}
```

But the query is looking for:
```
(`fv42`.`value` LIKE '%\"field42\":\"children-families\"%' OR `fv42`.`value` LIKE '%\"field42\":\"youth\"%'))
```

So there is never a match. 

In cases like this I would expect to have an article return if it matched either value, so the "OR" is correct, but the query doesn't work in this situation because of how the data is stored.

**Comment by nikosdion** [comment]
This can't be addressed **unless** we make it a requirement that your database server must support [JSON_CONTAINS](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-contains) since multiple values can be stored in any order and any combination.
